- name: run insights to obtain latest diagnosis info
  hosts: "@@HOSTS@@"
  vars:
    insights_remediation: "@@REMEDIATION@@"
    insights_signature_exclude: "/hosts,/vars/insights_signature,/vars/insights_remediation"
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTVlpCZDFWQldVaHBRblZqZG5jMU9FUXJhalZ3VGtGUmFtRkdVa0ZCYTBSVWNu
      UnZRVzFSVkRBdlFVODVaRlJyYlRablJHZHRabUkyVGxGMGFVNEtPWHBNYmtWcmRsaEpibVZQV2s0
      MWRGcDBPSEZWWmtaaFNYQnBSMEV5SzFGWU9GVlNaR2hWTDJOdmRIbDRLMWQ2UlZscU1sSlpaSEEz
      ZEVnM01IQXpWUXBpWjFwbVRGRTNkV2wxYm5NNGIwMXFaV3N5VURaVFVWcExXRmxhV1c0NVYyZENP
      V2R2VG5FMk9FZERXbXR3Um1KVFVqWXJTRVl3TWxwYVVUUlZTV0ZtQ21Ga05XSmplWElyZVVwbFoy
      TlFVVk5RYUhscmNtaGtaV1pQWm5ORk9YUlhlVmhXUjFwSk1ETnNXSGh3VEVaSlJsQlFZWFZRUzNB
      NE5WcHBha0Y0VjNvS2RHYzRTSGRGUjJzME5HRTFRa3BqYVdsdWQyNXJWV1pDVEc0NFVHeHVPRVF2
      TjNSc1NsZExUVWh4TmtsWVkwMW1NVzlVU1RKdWMzZDFXRkZzTUhsbWRRcHNUekYwVHpkWFpHVTJO
      QzlHT0dGdVptNVpUVUZ5TjNoamIxTTJaMU5sTDJWeWRuVnZOamt3YVVOWFYyWm5SV294WVhSd1Qx
      cDJjazF5YmxkSllYUlhDakZrYUVONFVqaGFabkE1UmxsQ2RXUnhZV05yYVhGWVNtNDBjbEppTTFo
      clFVWlNUVmQ0YTBseWJFVkdkRUZKYjJveVdrNDJabGRVYjJwQ1JVTmlRbmNLZG14RmQxWmxObGhR
      ZW5WYWVVRm9Sa0ZFZGxWcU1UZElLME01VnpCd1ZrcHlkM3BSVUV0cE1DOXJlRTFOZVV0UWJ6ZDNa
      R3BEU0dsalFtdHRRVk01TXdwR1ZYbzVUMWcxY0RRNFpIa3lhV1p6TDBOblIyMW5XWFZEWjI1UllW
      QjNWMkpHTUhkMGREQmlWVk55WldkUldWZ3JkV3hJTlhOQlJtMW9TVUZ1Ym1GdENsTkNWVUV5ZFZr
      MVpsZGlPVXhzTmpablIwcGlUSGxNY1ZSUVNFcFNTbWxXWjNKTEt6VnpTMHgyZDNnMmNqTXJjVnBr
      YTFoUVIza3hSM0ZTVlZKT1NGUUtXWFoxVm5sUGRIZHZVV2xCUm1rdlJYWmxPV05xV2xwdWEwcDVW
      MlZUV1RodVVtNDFlbll5TkhSUWJGSkdVVk5xZWtscWMxSlNhVVJvYzA1UWFGUlRhd3AxZGxkYVdI
      SjBWVlpoUlQwS1BVMDNMek1LTFMwdExTMUZUa1FnVUVkUUlGTkpSMDVCVkZWU1JTMHRMUzB0Q2c9
      PQ==
  become: true
  tasks:
    - name: obtain diagnosis info
      command: "insights-client --diagnosis{{ insights_remediation | regex_search('\\s[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') }}"
      register: insights_result
      changed_when: false
      check_mode: false
    - name: register insights report as fact for use by other plays
      set_fact: insights_report={{ insights_result.stdout }}
