- name: run insights to obtain latest diagnosis info
  hosts: "@@HOSTS@@"
  vars:
    insights_signature_exclude: "/hosts,/vars/insights_signature"
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTV05DUVVGQ1EwRkJSMEpSU201NE0xWTVRVUZ2U2tWTmRuYzFPRVFyYWpWd1Ru
      cHFZMUF2TVVoUGFEZDBWbVV6TkV0cFUyZ3dRMjlFUm5wcWRGUUtiRUYzYkRaaGVqaERWak12YjJR
      MVkwdGhjR3RPVlZVNVNsSkNURk5yUVdFM0wyTllia0UwUjJOM2JtZDNaWGcxYUhGT2N6RXJhVkJz
      WTNCQmVIbHRlZ3BFWjJ4aGRFbEtkaTlyUlhkUU1YSlBUVmhNTUVScmIzY3lhVFYyVTFwUmEwVXph
      MjgxTTNaYVVXczNXRE40Y1hWWlJVSTJjVFZwZFc5eE1tTkNiSFJWQ2pacVlYSmFRbFF5Y25SalRU
      UXlSa2hqYkUxcE0zaEJabmxIV1dGM1ZHNTBiekpTYjFBclFrZFhaWFozVkRSbFVIQk5ObEkzZDFJ
      MFpHUktUbWxRUzAwS1RuVm5jMWxLWm1RM1dqRlJhazVhWjAwMlFtOHpUa3d5VnpONlZtdHhTVlU1
      TTFGMFMySkhVWFJTVVZadEwySm5NRFU0U21ZdlJqQlBlVGd2ZEVacGRBb3lhSEo2U1hseldERjVN
      SFZCUnpSTVZWcEJaRmhUU1dFdllXNWFXSHB2Ym5keVNuQkdja2x3ZFhSQ1lUWXlaMlF5VTJ4TFNE
      aFVNM0pKZEZaWWRGSnlDa2hHVEhGalR6ZHpUbmN2T0dKWlVtTlpiWFYyWlZaVVdYbFRRVk5UVkZK
      S01WcHpjbWhvVlZsMVRGUjRaMlJhTnpkSWFFaFpVR0pxT1d4RVFtdG1RbFVLY25OdmIzVnhabTlN
      WjJ0Qk1sQlVjRkJ6TWxobWRERkxRbk5LY0dwd1UxZFlTRlJPYmtFNGFFWnNUM3BGU1ZSTVpuSkhO
      Rkp5YzJkeE5EWk1iVGxOVmdvdmJtWklRVEpHYnpSUFEzUmlja1UwU0VWVVNGZE9kbFpJY0dGd01s
      RnRkekZ5VFRWUGIyeEViV2xSY0ZVMVFpdHBiVEpwYm5RMmRFZEVZMFY1TVU5RUNuWkVVblJLWjBa
      RmJtNUhabVpzT1hKT2RtOVRUVWhXYVU5a2JtZDBRMlo2VURsWVdXTkRSMWhHVWt0c09IaEZTbEJ5
      TVVSQk1tdEVjbkZMYlVaMFUwb0tVWGhwYmtOc2RscEpZMlZHUXpsSVdESTFRakJvYTJ4aE1HMTBX
      WGM1WmxaemR6ZE5VVVZ4VGpjMmNUSkZWMUV2VVc4M05WaFZVbTlKTTBGWlRUSjBXUXBaVmtwNFpY
      QlFRVTVyV0c5WVFrMTRXa1E1WWdvOVJXMW9Od290TFMwdExVVk9SQ0JRUjFBZ1UwbEhUa0ZVVlZK
      RkxTMHRMUzBL
  become: true
  tasks:
    - name: obtain diagnosis info
      command: "insights-client --diagnosis"
      register: insights_result
      changed_when: false
      check_mode: false
    - name: register insights report as fact for use by other plays
      set_fact: insights_report={{ insights_result.stdout }}
