# Automatic system reboot was suppressed for this playbook.
# This play lists the systems that need to be rebooted manually for the changes to take effect.
- name: Reboot reminder
  hosts: "@@HOSTS@@"
  gather_facts: false
  vars:
    insights_signature_exclude: /hosts,/vars/insights_signature
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTVlpCZDFWQldVaHBRekZ6ZG5jMU9FUXJhalZ3VGtGUmFHaDNkeTh2VVV4SFJE
      aFFNM1l3VlhKWmRFUldabGhaUWxWSFNGQkpUbkpNV1ZCNFFUUUtXWFJXUmtFd1ZXb3diWGhyVVVG
      RFNtbHNZbVJGYVVWdVJIaFVZMVpDZDFSMlpVd3dTVWR0Um5sVVZVWkRVVEZ6WkdRMVUwc3JRMlJy
      TjJKa2RHTmliQW81TlRkaWJtZzVXbk5xYm14dWEwOU5ObTlyVFhVNFNraDZSMDFRV1hST01VaHdR
      VGxJYVV4Mk9IaEdPSFYzTmtkMWQycE9PREJ5ZDNaMmVIZG1WWEpOQ2psWFdYZE1PVU51UzJaRk16
      QnVOM04wTDA1TGJFbDFMMmd3Y2pKU1JTc3hPV1Z0TUdodVJsQmhaa2RwT1RZeWRXaFVTRGhZYzB4
      VWVHOXlRekZhU0c4S09VeENlRU5PVWsxc1draGljVGhzYVd0UVJsaFBhekkxTlNzdmFXMUdkazlE
      V1hwT1RuRXpkVkYxTDB0SWFGTTVhemRaT0Vwb0wyRjZTRFYzYW5KNlV3cDNNekJ1Y25JeVNVOW1j
      V0V2VUdWRlJXOU5SbUV3UVV4WWRFZFVSREpyWmk5Q1pIVXlSemRUU0hkMFNsaG9VbEJzVnpKNU9H
      MW1Za2wwY0UxYWMyTlFDbFp2WkhoVmEwbGtkVXhUTmpaM04wODBPRTVRT1V0Uk9XbE9Wa2hCTVdo
      NVZTOTFWekkwT1ZFd2EwWjZlR3BEUVhsR1QwY3pabkZRUkhWaWNVeFlkbkFLTjB0bFJGWklRbFpS
      UVVkckwwUnhSMFpYT0hoMlVUUkZkSEpVTldrMlVsb3hVRlJMZEZCVmNrVmpRV2hoU2xsWlMwRm9X
      U3R4Y2pkUE1WSkhkazFxUlFwTlEzbFFjVlZ1U0hJMFNHSmtjelJTU0drNVJucFFaeXN2VjB0M2F6
      VnRhMUJMTUUxaEsyMUxkVXd5YTI1elUwaDFTakEzVkVVMk1HNU1WbGM0YTFwakNsSllibGxCU1ZB
      d1RGUnRUMHhvWms0NWJtdzVOM2hvUTNSUFdrZFBjMVp3WVhWdlIyZENOV0ZrV1ZGYVZXY3JSVzF0
      UldSQ1ZrdDZOVUp2VERWc1pYTUtVMjVQVkd3dmFEbG9hekpqYm0xVVdWRTFRa1JoY1RSdGR6QnFS
      SGhDTjFWUWNVdDFZazFDUTJoSVdIUnRVRFpGT1hSU1pYRnNiWHB0YWxkR2QxWnpZd3B1TDBGRFpW
      ZzFZVUUxY3owS1BXZHFZbWdLTFMwdExTMUZUa1FnVUVkUUlGTkpSMDVCVkZWU1JTMHRMUzB0Q2c9
      PQ==
  tasks:
    - debug:
        msg: "Automatic system reboot was suppressed for this playbook. Reboot {{inventory_hostname}} manually for the changes to take effect."
      when:
        - insights_needs_reboot is defined
        - insights_needs_reboot
