- name: update vulnerable packages
  hosts: "@@HOSTS@@"
  vars:
    insights_issues: "@@ISSUES@@"
    insights_signature_exclude: /hosts,/vars/insights_signature,/vars/insights_issues
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTVlpCZDFWQldWTmFUMGM0ZG5jMU9FUXJhalZ3VGtGUmFFVnpRUzh2VW1OSFFU
      TjFLM2RDVFdOYWJTOTNheTlOVVVKRGVua3pRWEZsZG1Jd1NIa0tlRFZtTUZKWVoybHROVkpKTkRs
      YVVIYzRVak5EZDJGM1l6QTNUa0V5TjJOSFltWkRlbTF5TWpaR00zazNSemRKZG5ReldUUkpURGhs
      YUhsWmFHUm5SZ3B4YTIwMk5uWkllVWRsTmxnNWVWVmpjblJrUzNOWlFXRjFNWE0wTkhSVU5IQnJh
      MUpUYWl0VlJ6bHBUbGxWVEdzelUyRlNTMU5ZV0cxdFpVRnhiRXRZQ2tOMFV6a3hUVVpYWWtsS00z
      ZHlibTF0VFhKUmRXaDRlVUYwTW14TllWUnFkMDU1VDFoalRuQjFWR0pQWVZoSlRIRkROV1YwZFdn
      elRtZFpkV0ZLVVVFS2NVa3dZV3hNU21obWNsSkpVMlJLTkVNeU5YRk1aa2M0U2tKb1RXMTNRVkUy
      VlhaM2N6VTJZaXRhZDIxWGEyTllaM28xV1ZwWVNHbERaMjF3V0ZNeFJncG9SbE0xVlU1YWNrYzNP
      QzlTVGxGVmFHRTBiMkVyTDNsck5WWm5UVlZsYkVSV1EwaHhSMFk1YVdkWlVtdENiVk5UZFROc1RW
      cFZZbU53Wms5eU5DdE9DbUZxVTJoSGRXaHdhMjlzTTFOSFNVWTFaVVZLYW5CWGFURlJSak52UTFS
      UWVtMXVjM0p1TTNWWlpYTmtObWhCU1RGcFpIVnJVVGg1UW1sbk1EaExiR2NLU1hnNGMwaE9UeXQ0
      TUhWcVJrRlVWalpDV2pCUU9HOUViREpHTjFCSlkwSkxWMnRsWldGM1pGaGFNWEpNVFRVNGVESnJa
      V1J3VG14WldIaG1aems0VEFwRVlrZHJSVUpDVFd4MU1uUjJia2w2V0RsamNqUnVNVXRKZEZsTFpr
      ZGhUbkpUYkZsWVJ6bG5TbG92YUZsTUt6ZHhPRk5TU2tsb1FUSkZkRTF4Y1VndkNteFVWVUpYZDBO
      aVRuSnJjM1pGTWk5WE1VTnRTWHBOVDNsRVZuSTVibkZLTDFVclVYQnFWMU5HY2tWb1JHZEpOazFs
      WWtOblR6SnVXVmxVTnpoM1MwZ0tSVWs1T1doblF5OHJOSGRYZFVkeVFVSmtlbnBLWm14YVpXZHRO
      RTVaSzBOTFNHOXVUa28yYmxKaVYxUlhaMDV5TjFrM2VVcGhiVVZRUTFsd1FYTnlSZ3BpTTJveU1G
      cEhWblp3TkQwS1BUaDBjbkFLTFMwdExTMUZUa1FnVUVkUUlGTkpSMDVCVkZWU1JTMHRMUzB0Q2c9
      PQ==
  become: true
  tasks:
    - name: check for update
      shell: "{{ ansible_facts['pkg_mgr'] }} check-update -q {{ insights_issues | regex_search('(--cve (CVE-[0-9]{4}-[0-9]+)\\s*)+') }}"
      check_mode: no
      register: check_out
      failed_when: check_out.rc != 0 and check_out.rc != 100

    - when: check_out.rc == 100
      name: upgrade package
      shell: "{{ ansible_facts['pkg_mgr'] }} upgrade -v -y {{ insights_issues | regex_search('(--cve (CVE-[0-9]{4}-[0-9]+)\\s*)+') }}"

    - when: check_out.rc == 100
      name: set reboot fact
      set_fact:
        insights_needs_reboot: true
