version: '3.8'

services:
  # SpiceDB - the authorization database (managed by Kessel)
  spicedb:
    image: "authzed/spicedb:latest"
    command: "serve"
    restart: "always"
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - SPICEDB_GRPC_PRESHARED_KEY=somerandomkeyhere
      - SPICEDB_HTTP_ENABLED=true
    depends_on:
      - postgres

  # PostgreSQL for SpiceDB
  postgres:
    image: "postgres:14"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=spicedb
      - POSTGRES_USER=spicedb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Kessel Relations API
  kessel-relations:
    image: "quay.io/cloudservices/kessel-relations:latest"
    ports:
      - "8081:8080"
    environment:
      - SPICEDB_ENDPOINT=spicedb:50051
      - SPICEDB_TOKEN=somerandomkeyhere
      - SPICEDB_INSECURE=true
    depends_on:
      - spicedb
    restart: "always"

  # Redis for caching (optional)
  redis:
    image: "redis:7-alpine"
    ports:
      - "6380:6379"

volumes:
  postgres_data: 