- name: update packages
  hosts: "@@HOSTS@@"
  vars:
    insights_issues: "@@ISSUES@@"
    requires_reboot: "@@REQUIRES_REBOOT@@"
    insights_signature_exclude: "/hosts,/vars/insights_signature,/vars/insights_issues,/vars/requires_reboot"
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTV05DUVVGQ1EwRkJSMEpSU20xWU5VdDBRVUZ2U2tWTmRuYzFPRVFyYWpWd1Ru
      VTNZMUF2TVZGeGFuVkNUR1p4Y0ZFNVVpOVdkblYxWVVaVk1YSUtaa2x1Y3pSMFNWZHBSM3BGZEUx
      c1ZEZGtZMHRhZG5wM2MzY3lOMEZwV1ZKVlVGSXdURk5ITlVKb2NXdEdaMmwxVUUxSlkwNXZlbmRI
      TUVScU5IWjRkd3BQZVZWbU5XSmFaWGw2TDNnMlpsTk1hMVIwZWpOMk1VSjFVWFYxTlhWRlMxWnBX
      bE5GWXpVeGFWUnphVGgyU2tGRFFreFRWbTk2V2toUVN6aEJURkZJQ2tabk9VTlZhVk5pVTJKYWRq
      TmtlUzl4VUdkS1FUaHVVVEZQUkVwblYyWm1lRXBsVFZSWlpFNW5VVWRpT0VOMWVHOW5WMWRLYWtW
      V09YUXdSMXBDTm04S2VXNDBiSFpsTUhZdmNGQTVSWFl2ZUVwUGFHUXljMWxvWjFWbWNteG9XRTQ1
      V0ZweGJuaExlaTlsTUU0eE9FdG5RbWRYTURGNmRGVlhRVkl2TVhscWNBcGFlamdyVWt0NVdEQnBW
      SEZLZWpWVGNWSjBiMlZZV1U4eloyNXViV2R0ZG1jM1dqbFRjMHR6ZVdzd1UzaExhRkF3WmtnM1Yy
      MHljbmRoTWpsNFFpODRDbUp0YVRoNWR6TktTRUZvYzI5WmNGcDZUMGxuT1hGYVJYZGFZV1p3VVVS
      UVJFMWpVakJaUmtkWk4xZHpVMkpETVRKNVVuRkpNbTgzY0dSUEt6WlViMUVLUkdweE5qbE5hR1Vy
      TUZsUE9HOURUMWxQUWtKa1R6Sm5jaTkwYjFKaUwxWnBMeTl6VDNkMVdHdHZWeXQzYjFaMFdXczFU
      R28wVlRWUFQzbENjMlZMV2dwU1RUWjVORnBCY2tWdlpTODJhMUZNV1hsaVEwbFFPRGM0UkVOT1Rq
      bGpOMmd5UTFoRWNXNTZlWFJFT0ZNMWRXRnZkMlpoUnpoV09FVXhWR3AwWjFseENtZFpaVXhITVV3
      MVExTTNkbFJ4UzFSUWRIbE9VREkwZVRKeFExZDFhVzlDVGt0NmJFdzJSVXBQTDJwaGEybExhbTFH
      Wm05T1RTdFViRlY1VjJKUWQxRUtlbXRRVVdkUWRWcDBSbTFCVm01Qk9IVXJjVlJ1ZFdWeFVHWk9i
      MVJ6TWxSV1ZXeE9UbEI0UlZOSGJFUkpNSHBDWVhCbmNHTkhVUzlzWlRGUVR5OXpZZ3BWZW10SmMy
      WkxWMnhuUzJJemJYaFBZMmgzTndvOVpYRTFUQW90TFMwdExVVk9SQ0JRUjFBZ1UwbEhUa0ZVVlZK
      RkxTMHRMUzBL
  become: true
  tasks:
    - name: check for update
      shell: "{{ ansible_facts['pkg_mgr'] }} check-update -q {{ insights_issues | regex_search('(--advisory ((FEDORA-EPEL-[\\w-]+)|(RH[SBE]A-20[\\d]{2}:[\\d]{4,6}))\\s*)+') }}"
      check_mode: no
      register: check_out
      failed_when: check_out.rc != 0 and check_out.rc != 100

    - when: check_out.rc == 100
      name: upgrade package
      shell: "{{ ansible_facts['pkg_mgr'] }} update-minimal -d 2 -y {{ insights_issues | regex_search('(--advisory ((FEDORA-EPEL-[\\w-]+)|(RH[SBE]A-20[\\d]{2}:[\\d]{4,6}))\\s*)+') }}"

    - when: check_out.rc == 100
      name: set reboot fact
      set_fact:
        insights_needs_reboot: "{{requires_reboot}}"
