- name: update packages
  hosts: "@@HOSTS@@"
  vars:
    insights_issues: "@@ISSUES@@"
    insights_signature_exclude: "/hosts,/vars/insights_signature,/vars/insights_issues"
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTVlpCZDFWQldWTmFUbmRqZG5jMU9FUXJhalZ3VGtGUmFYcEZkeTh2WmtRNFJV
      aFBOa3BYVFZWNVlUVXJVVk5ST1hKaWJUTlVSSEV6YkhSMVVVd0thblZLVDJzNGIyMU5RbTl4YzFS
      TGVFMVdjamxzT0ZReWJrdGtRblZYVTFGV1ZtdFdUVTh5TUUxRWNrTndSWEV3UVhsUGFWcEhkWEFy
      WkZvclIzaEtlZ3BtZERsM09IQklTRVV3ZFhoUWRqaFFNbmhYUzIxc1oybG1TRXMyVTNvME1VVTFN
      SFpSZEVRMGVuRnNaWHA2YUU1aVNXZHJZMWRWSzJocVlqVkpTbXB4Q2xsWFRUaEJOa3hpYUZwTGRF
      SnRVMHBKUVhKUFQwdEhObE5yVm1sSFlXd3lhVVlyUkV0eWVYcHJVaTh6UldzMlRuQTBUaXRXU0ho
      cVlVZ3JNM0E1ZVdrS1Fpc3lSVnBGWjNkalFXOXNNaXRhYUhsM1N6VlhSa2RIUzNaQlIyZzFTRkJ3
      WVc5clNqSkJOMlZyVEZCaFpuaFpNV1ZSVGt4RmR6bFNjVlpJT1hKSk1RcE5iekZ6ZG5kR05XdGxl
      WFl6WTJKeVRUWTFjbWt6VkUxMVZYVlRSbGxTV1ZKVlRGSlZVR2xFSzNVNWJ5dHBRMUJ5ZDNORlNW
      VkxkbUV5TkhKa2FtSXpDbGxpUmtOelZ6WjJiMjl3Um5kcVlWSXpablUxUkUxWmJYcDRSVzFYTWs1
      TlR6ZEtjbWQ0TXl0WWQwVk1ibk5IUm1SbldrUk5OaTlXYm14UGNrOVlia01LUkZWTU5tNHJia2gz
      TjBkM0wwWTVkblI2YW5veE1VMUlhRzh6ZEdOVGVVMHhUVEV5U0ZsQ1RqZGxSWEEyUzJOa00zRkVT
      a28yWlV0MFdYZEZRbGN5UndwRVZUUnBUa2gxZEVGQlZYTkxibmd6Um5GQlZEaHhSSFJYWlRSRGJq
      bFhMMkptUTBkQ09YRlFUMWRpWkZrd05UZFFielZzU0dKWGFVYzRTR0pLY21aNkNuQkVTelJTYTJw
      WlEwWjRkV2xQVG05d2RURjNTMkZpUTNsUmJWZGxWV0ZtYVZCYVkxZEVXQzlyTDA5bVRrdDNabGxr
      ZUZsbE5rcGxRMHh0TkVOYVlYSUtabUYwU0ZWVVJWbFBjVUoxUVRSb1F5OU5XWFF3T1RKNGFEVnla
      SEJaVjI5U04xcHRVSEY1SzFSMFdIWTVPVVZxUkhsNVNtbE1UMkp4ZFhsWE0zaGhNd280ZFhaaU9Y
      SjNXbXhZYnowS1BXUlZZa3dLTFMwdExTMUZUa1FnVUVkUUlGTkpSMDVCVkZWU1JTMHRMUzB0Q2c9
      PQ==
  become: true
  tasks:
    - name: check for update
      shell: "{{ ansible_facts['pkg_mgr'] }} check-update -q {{ insights_issues | regex_search('(--advisory (RH[SBE]A-20[\\d]{2}:[\\d]{4,5})\\s*)+') }}"
      check_mode: no
      register: check_out
      failed_when: check_out.rc != 0 and check_out.rc != 100
      args:
        warn: false

    - when: check_out.rc == 100
      name: upgrade package
      shell: "{{ ansible_facts['pkg_mgr'] }} update -d 2 -y {{ insights_issues | regex_search('(--advisory (RH[SBE]A-20[\\d]{2}:[\\d]{4,5})\\s*)+') }}"
      args:
        warn: false

    - when: check_out.rc == 100
      name: set reboot fact
      set_fact:
        insights_needs_reboot: true
