- name: update packages
  hosts: "@@HOSTS@@"
  vars:
    insights_issues: "@@ISSUES@@"
    requires_reboot: "@@REQUIRES_REBOOT@@"
    insights_signature_exclude: "/hosts,/vars/insights_signature,/vars/insights_issues,/vars/requires_reboot"
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTVlpCZDFWQldrWjZOR0U0ZG5jMU9FUXJhalZ3VGtGUmFqRmhkeTh2WTJveWMw
      TmFRbWR2VW5Cek0xTkpjazFFUkZWTGIxQTFWak14YlhrMVRUSUtUSFp0UzBac1FWZ3pPRzVTZUZw
      UVpXSnViVUZJYWpoNE0weFdTVWxTY2pOTVdFUmxSVXB0YVdGWFZXVmtWV3QwUm01NllXRk1ORnA0
      VkhoVFJGazBUQXBQYzNaU09XaFdkVm80UWpJMmFXbFdTM2RsY21WeFdUUkVaRWM1TUdoUldXUlFN
      V3RFVTBSb1RWTlpVUzkyZEVoQ1NFbHFZemRpTlM5dldFUlRaMDFLQ210bVoyNVNjVGhsTlVObkww
      RjVRV0paYURrMVJUSlZjbFIwTkRCR1VqRmhhbFI2VVZwSWMwOHhabTVSTUVKR1RqazFOMnB6V1dk
      TlRVbDBZbWhQVlRRS1FWVlVTekZ4UTBVNFFYbHROMk40VEhCc1dWZGlkbVF2UTBWVVNsTmllR05o
      Vm5sRU5GSjFSRTVGY0VaeFZXRnRhbTE2V2xKc2JESlZUVGMzVVZwT1FRcFNWMDQzYlROSWIwMWlk
      VUV2WTJaUmFHRnlaMEpwVWtsWk5TdEJTVkYxWmtSa1FWbE9UMHR4ZWtSUlUyNVpVbFUwTDJWd2RV
      MVVTVVpXVDBJM1JuSllDbGsxUkc4dldub3hlVE42ZGpGSGVtZElaRzV0U25CVmFEZFliV1pEUkVs
      SFR6ZEZRWFZoV1RSVmVrTmxXRTlJZDJWS0swbHZiMWhCVFhSa05FSlRaVllLUlhCSloyRXJhV2RV
      ZG5sUlFWQllNMjlWV0dGSGJ6bFRSa3BQZGxwS1JuaENVVWRuZUc1elNubFFjbFJYVDJwWE0yY3hO
      Mk5vTTNwc1NYVmhTMUJ1ZFFwelFpOVNSemRTWW01R1kyRllTbEJSV0hGd1NHMDVUMHBrYVhJeGEz
      bDNUSEp6TUhkcE9XOVdhWE00VWtSck9EZFpjVlpaSzFoSksyRjJabWxETURFeUNqWmFLMU42YVdW
      c2VISnZRMWx2Yms4cmRWbzRkWGRKVUZCcFR6YzNOVTlzUnpOcmJtTk9XbTVyYlZGVlpHUldSWEJI
      WldwSVREWllNbTVXVkVWeVJtMEtaamhJYlZoUk1EUkpXak5IZUhOeVUzQllZa2xqUkVwVWNtWnJT
      azlCVXpjNWFYaHZVVEphYzI1WE5FUmFOVGRqYjNRd1JtOU5la2w1ZUhodVIxSkNZUXAwVDFreVkx
      VnNReTk2TkQwS1BVazJUM2dLTFMwdExTMUZUa1FnVUVkUUlGTkpSMDVCVkZWU1JTMHRMUzB0Q2c9
      PQ==
  become: true
  tasks:
    - name: check for update
      shell: "{{ ansible_facts['pkg_mgr'] }} check-update -q {{ insights_issues | regex_search('(--advisory ((FEDORA-EPEL-[\\w-]+)|(RH[SBE]A-20[\\d]{2}:[\\d]{4,5}))\\s*)+') }}"
      check_mode: no
      register: check_out
      failed_when: check_out.rc != 0 and check_out.rc != 100

    - when: check_out.rc == 100
      name: upgrade package
      shell: "{{ ansible_facts['pkg_mgr'] }} update -d 2 -y {{ insights_issues | regex_search('(--advisory ((FEDORA-EPEL-[\\w-]+)|(RH[SBE]A-20[\\d]{2}:[\\d]{4,5}))\\s*)+') }}"

    - when: check_out.rc == 100
      name: set reboot fact
      set_fact:
        insights_needs_reboot: "{{requires_reboot}}"
