- name: update packages
  hosts: "@@HOSTS@@"
  vars:
    insights_issues: "@@ISSUES@@"
    insights_signature_exclude: "/hosts,/vars/insights_signature,/vars/insights_issues"
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTVlpCZDFWQldrWjZOR2RqZG5jMU9FUXJhalZ3VGtGUmFubDVVUzg1U0hoU1lq
      QjVUSEprZDJaeWRTdERjMmhqVXpVNFMyNURURW8xUTJaM1dGY0tjVGh2VVZsSFVtaElaMDlCY0hw
      Q1pXTjFSV3RNTWtWR1psRXljbXBFYTFwVGVYbFdWR1ZxTm5admVrdFZVMjlZVEdWWVUxZElRMlpy
      WjNkMFJYSXJXQXBzT0hscVpsVTBVRkJ1YnpoS2NGbEZhRXBzVjNBMlVGZG5PRzFuSzA1cmRXaFRN
      SGN3Y0VSRWNHbElUVzlEVDJKc1NrOVlVbVozV2k4NFZUVlBPSFZNQ2xWSlFtUklha3hGWlRZeWVX
      RXlSa2N4ZUVOQ1lsZHZURTlOVmxkdFYxRmhhbko1T0doT0swSmlaRmR0TnpOdGVWVlhVRWRTYlhw
      UFZIRkxiRFpZZDI0S1RtMVhOVVJLZG1WSFRFUmtTR1F5ZUhKUlZVTkZiVzR5U3l0SUwwWTJVMlZT
      TUZRMmMwSjFjVTlLVUhGUFVtd3pPRFEwUkU5bU1sbHhibVpwT0dSclZRcFpiRVJPVmtreGFIQlNk
      MUJ0WXpVcmJHMVZkRXc1ZWxoeE1FZzJXREJDYkZrMlJrZEpVbU5IUmxsR2JXWmtkVUpCVkdWR1Mx
      aGtOVVZyVm5kcVdERkRDamg1V25kSVNtWTVLM1ZIUkVnNU5uUklPSFpOTkZSQlJrbFJZa1IyU0VW
      UE1razJNWEpzUWtzMVduZGFjblZ6U1RWdVdYTlJSRmRUV1dac2RXdENSWGdLTURSUWVFWlNMMFpo
      WmxoQlFYVmhXVE5rUVdGMVEzVTNPVmhpZURSdVJtWnNURkpsV0hKdmJteElUbkJPVlRaRVdERm1N
      bk00UzNKd01rTk9aV0l6ZFFwRmIwVkRVR3R5VVVOM05sSlFhekpvVEVweVVUUkhkR1pOT1RSTFdY
      TkhSbTFXVUVwNFYzcG1lWEJHUzB0RlNVTXZjMGxVZDB0RFFuQmFNMHRET1VjckNrWnVWbUZzU0dK
      M2EyVk9SalJVY1VsNldYZHFNa2R5VkRSV1pWSjFNekZJVjIxWVFtbDZVa1JUVlhaNFN5OTJOVU56
      T0VwWlprNW1jRXg1ZUhsTGFtMEtOR0kwUnpWMWRFOTRjbE5RVXpSVU1GUk1SbWt5VDJZM1NpdG1k
      bFp1UW5sV1NHd3haR3BPY0cxdWVtVnhNV3RsVjNkM2RXNVplR2xyV0hoRWQyMTZSZ3AzTWpkb09G
      WTBkalJqUlQwS1BYbFRWRGdLTFMwdExTMUZUa1FnVUVkUUlGTkpSMDVCVkZWU1JTMHRMUzB0Q2c9
      PQ==
  become: true
  tasks:
    - name: check for update
      shell: "{{ ansible_facts['pkg_mgr'] }} check-update -q {{ insights_issues | regex_search('^(([0-9]+):)?([^:(/=<>;]+)-(([0-9]+):)?([^-:(/=<>;]+)-([^-:(/=<>;]+)\\.([^-:.(/=<>;]+)$') }}"
      check_mode: no
      register: check_out
      failed_when: check_out.rc != 0 and check_out.rc != 100

    - when: check_out.rc == 100
      name: upgrade package
      shell: "{{ ansible_facts['pkg_mgr'] }} update -d 2 -y {{ insights_issues | regex_search('^(([0-9]+):)?([^:(/=<>;]+)-(([0-9]+):)?([^-:(/=<>;]+)-([^-:(/=<>;]+)\\.([^-:.(/=<>;]+)$') }}"

    - when: check_out.rc == 100
      name: set reboot fact
      set_fact:
        insights_needs_reboot: true
