- name: update packages
  hosts: "@@HOSTS@@"
  vars:
    insights_issues: "@@ISSUES@@"
    insights_signature_exclude: "/hosts,/vars/insights_signature,/vars/insights_issues"
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTV05DUVVGQ1EwRkJSMEpSU20xWU5Vc3dRVUZ2U2tWTmRuYzFPRVFyYWpWd1Rt
      bEVkMUF2TVZOVFZXdHJUa3BoVXpWVk5UTnlSbGxqU2l0QmVIRUtOMmhYWmpjNU5rSjJLekkwZFc5
      NU9YbEhXVlpHVkZsSlJVUm5VRWRRTVZKTVFtMXJiRVV3U2l0RVVHOVJUVE5JVjFaWE1Xa3dXRk56
      YlZBekwzcGpZUXBCTVhnM1RXcDNPVU12YmpWblkydFJNa2hLVWsxVkt6Y3ZORkpJWVdOVE0weHNX
      bmRVTTNkNk4xaFpNakZKUWs1aFNGcGtTMjByZFZWNmNYZFhSbEJ6Q21KUVp6QnpRVU40V2pSM1VH
      SXZReTl1Ym1nNWFYcDJRbFpGVVVVNVdFcExhRlZLU1RGR1NGZFRUU3RMWWtaek1YcHhPSGw1Y1VO
      cWQweFlXbWN2Y2xNS2MyNUpSRWRVY0c4MFUxTjRiSFZXY3pOQ016bGpha0p5YjB4V01FbHFka2Qx
      UzFSS2MzUXZNa1V6WmxSa1RrNVpjRE5uVTAxWlExazVSbU5CWlZGNVpBcHdkMVZvTUVWMFNrTlVV
      eXRaV1ZrelVXaHJVMkpsYWs5WGVrdExOVWxyYkRkSFQycERXVlV2Tm5OSGFGSXZTalpJTlN0R2JG
      UklTamhaUW0xYWNYVkNDak12TDAxSVdIbDViazVRZFVod1RWaG5PSFZPWW5OaWNGVjBiRFJFVWtv
      cldHcGFXbTR5V1RkUlNIQlRhak53T0RsMFdHZFpVMk4yUzI1UE9XZDRTSE1LSzJWcWVtc3pRM293
      WVUwdlpVZHdRVFozUjI1ek5IVm5NME50UjJWVmQwYzRiRXcwVG10dmJGbGxWa1pEYldoeGFYaFhl
      REZpVmtKQ04waHhNV2wxU3dwT1l6UldZMnRXUkZwUlRrcG5jRlZCWjBSd1dHUjNTMHhWU0hGdGF6
      Z3lkMk55ZVhWcmVWVnBLMmMzTXk4MGNrOHpkV05DTkdZNWVFaEpWMk5EVWpJNUNraHVRVVV2Wm5K
      b05sVmlZVTUzYzI0d09FNWlTMUl6S3k5WVJVSnlkVmQzT1daME1GVnZPV3hXTldoS1oyY3dZa1Y1
      WjJSclMxVkdUMVpUT0ZGeFJVc0tLMWxXUlhJelFUQkROMkZHSzBvdmFUbGFlVWxYVDJSNVJHdHdU
      RWcxVFd3NVNYbFdUemRwVjA1Wk1qWktWRXA0VmxadlVXNU1jQ3N6Tm5JdlJXMDNhZ3BsZG1GU1RU
      UkRNMEpYY1VrdkwwbEpWRWxpTVFvOVJqSlNOUW90TFMwdExVVk9SQ0JRUjFBZ1UwbEhUa0ZVVlZK
      RkxTMHRMUzBL
  become: true
  tasks:
    - name: check for update
      shell: "{{ ansible_facts['pkg_mgr'] }} check-update -q {{ insights_issues | regex_search('^(([0-9]+):)?([^:(/=<>;]+)-(([0-9]+):)?([^-:(/=<>;]+)-([^-:(/=<>;]+)\\.([^-:.(/=<>;]+)$') }}"
      check_mode: no
      register: check_out
      failed_when: check_out.rc != 0 and check_out.rc != 100

    - when: check_out.rc == 100
      name: upgrade package
      shell: "{{ ansible_facts['pkg_mgr'] }} update-minimal -d 2 -y {{ insights_issues | regex_search('^(([0-9]+):)?([^:(/=<>;]+)-(([0-9]+):)?([^-:(/=<>;]+)-([^-:(/=<>;]+)\\.([^-:.(/=<>;]+)$') }}"

    - when: check_out.rc == 100
      name: set reboot fact
      set_fact:
        insights_needs_reboot: true
