- name: update packages
  hosts: "@@HOSTS@@"
  vars:
    insights_issues: "@@ISSUES@@"
    insights_signature_exclude: "/hosts,/vars/insights_signature,/vars/insights_issues"
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTVlpCZDFWQldVOWpRVEJOZG5jMU9FUXJhalZ3VGtGUmFraHhaeTgyUVhZMFJI
      QmtabEppVlhSaWFrTnNSbVYyTmpSMWRHUkZSbFo2Y2xwTmFTOEtOME5xVFc0dmIyNWxSR0U0ZFhN
      clRqVkRPR1J5Tm05c1YxbHBRMU5aWW5CTFptMU1LekF4UkVGVWFqTkVRVVUyVW1GSVpXVmxMMDE1
      U2pWNVYybHBkQXBKV1V0M1IzQTBUWEJXVDNOSFJ6bFNOVmxaUzNwSldtRkdkR0ZhZERaMk1uQkhU
      MEpxYUZsdk4zRkhNV0ZJUkZwNmEzVnVSVVZRZGs0NVprMUNaRnA1Q2trdk5sRlZUeXRRYlhsTlNV
      VjFVV2RPV1hReWNVZHJUSFpTWjFwVlRHaE1kV0l5Y1dwUlozTkVaVmQzUmxOb1dsbFdXVEoyUm13
      d2VGUlNjVXRPU21ZS01HZDZVMUpJTW05Wk5VZElXVlZYZDFOSVEycFZXbWxHWTNVNGFYTXZOVU5G
      Y0RCNlJFbHdNVEZMY0c1bWIyVTNUMVpOWmxCSlFrZzVhakJETVRKd1FRcEhaemRuVDI0d1lXVklU
      R3RMUlZCT1lXY3liVTVUS3pNemNVaE9kakF5YjFZMmJrTkdSMGt4VjIxa1p6UlhTakZ0YUdkVmVU
      VkhkR2QwUVhJM01uaEVDbVpoVkVGNk4wRlhUakpuZGtadk0zRm1TSEEyTlZOek1XZG5VVUV4TTNs
      TmRsQjNOV3N6VUhwWE5XcGlUbUl3YXpJeVdFaENTVlE1WVhGVVJUUlpUWE1LVWs0MGMydFVPSFJu
      WTBKdVkzQjNWWHB3WlZkVGVFTkZSMU4xTWs1QmFtSlZaM3BIVVdWMGNHOUxUVTB4ZUZSVmJXVnpS
      M0p0ZDFGNVYyMUdjV2xSVVFwUk9EaExlbTkwWmxWbmJWSnFWRGxMUmxNd2NFbHhPQzlKYmxKTVFq
      QkdPQzgxU1ZVMk1qQnlVemRSVGpSV2QycFhRbmRuV0Rsa1QzSmpTSFpSUWxsSENqaHJjbFl5T0Va
      Rk1uVmpRbEI1VGxkUU1FcFhTemhDVkVaVFIxUlNlbVJXV1VkRWJIQXpWRmczZG0xSWRqUnlVM3Ax
      YW5WVWNVRjBkV2x1UmtwUFpua0tlR3hSV2k4M0wwdE5kRTEyVkhBelFuVlFUbWM0VDNKMFlqUmxO
      bGcxT0VGM1pWWjJkbVUxUVRWc2QwczFabkptTVc1b05XNTZRWGxvY0hvd05XMUtSQXB6V2taT0sz
      UXdNM2x6YXowS1BTOVhiR1VLTFMwdExTMUZUa1FnVUVkUUlGTkpSMDVCVkZWU1JTMHRMUzB0Q2c9
      PQ==
  become: true
  tasks:
    - name: check for update
      shell: "{{ ansible_facts['pkg_mgr'] }} check-update -q {{ insights_issues | regex_search('^(([0-9]+):)?([^:(/=<>;]+)-(([0-9]+):)?([^-:(/=<>;]+)-([^-:(/=<>;]+)\\.([^-:.(/=<>;]+)$') }}"
      check_mode: no
      register: check_out
      failed_when: check_out.rc != 0 and check_out.rc != 100
      args:
        warn: false

    - when: check_out.rc == 100
      name: upgrade package
      shell: "{{ ansible_facts['pkg_mgr'] }} update -d 2 -y {{ insights_issues | regex_search('^(([0-9]+):)?([^:(/=<>;]+)-(([0-9]+):)?([^-:(/=<>;]+)-([^-:(/=<>;]+)\\.([^-:.(/=<>;]+)$') }}"
      args:
        warn: false

    - when: check_out.rc == 100
      name: set reboot fact
      set_fact:
        insights_needs_reboot: true
