---
apiVersion: v1
kind: Template
metadata:
  name: remediations
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: remediations
  spec:
    envName: ${ENV_NAME}
    optionalDependencies:
    - advisor
    - compliance
    - config-manager
    - inventory
    - patch
    - playbook-dispatcher
    - rbac
    - receptor
    - sources
    - vmaas
    - vulnerabilities
    database:
      name: remediations
    inMemoryDb: true
    deployments:
    - name: remediations
      minReplicas: 2
      web: true
      podSpec:
        image: quay.io/cloudservices/remediations:${IMAGE_TAG}
        initContainers:
          - env:
            - name: INIT_CONTAINER
              value: "True"
            - name: EPH_ENV
              value: ${EPH_ENV}
            - name: ADVISOR_IMPL
              value: ${ADVISOR_IMPL}
            - name: ADVISOR_HOST
              value: ${ADVISOR_HOST}
            - name: BODY_PARSER_LIMIT
              value: ${BODY_PARSER_LIMIT}
            - name: COMPLIANCE_IMPL
              value: ${COMPLIANCE_IMPL}
            - name: COMPLIANCE_HOST
              value: ${COMPLIANCE_HOST}
            - name: CONTENT_SERVER_HOST
              value: ${ADVISOR_HOST}
            - name: CONFIG_MANAGER_IMPL
              value: ${CONFIG_MANAGER_IMPL}
            - name: CONFIG_MANAGER_PORT
              value: ${CONFIG_MANAGER_PORT}
            - name: CONFIG_MANAGER_HOST
              value: ${CONFIG_MANAGER_HOST}
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: db.host
                  name: remediations-db
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: db.user
                  name: remediations-db
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db.password
                  name: remediations-db
            - name: DB_CA
              value: /opt/certs/rds-cacert
            - name: DB_SSL_ENABLED
              value: ${DB_SSL_ENABLED}
            - name: FIFI_TEXT_UPDATES
              value: 'true'
            - name: FIFI_TEXT_UPDATE_INTERVAL
              value: '5000'
            - name: FIFI_TEXT_UPDATE_FULL
              value: 'true'
            - name: DEMO_MODE
              value: 'false'
            - name: INVENTORY_IMPL
              value: ${INVENTORY_IMPL}
            - name: INVENTORY_PORT
              value: ${HOST_INVENTORY_PORT}
            - name: INVENTORY_HOST
              value: ${HOST_INVENTORY_HOST}
            - name: LOG_LEVEL
              value: ${LOG_LEVEL}
            - name: LOG_CW_ENABLED
              value: ${LOG_CW_ENABLED}
            - name: LOG_CW_KEY
              valueFrom:
                secretKeyRef:
                  key: aws_access_key_id
                  name: cloudwatch
            - name: LOG_CW_SECRET
              valueFrom:
                secretKeyRef:
                  key: aws_secret_access_key
                  name: cloudwatch
            - name: LOG_CW_GROUP
              valueFrom:
                secretKeyRef:
                  key: log_group_name
                  name: cloudwatch
            - name: LOG_CW_REGION
              valueFrom:
                secretKeyRef:
                  key: aws_region
                  name: cloudwatch
            - name: MARKETPLACE_CHECK
              value: ${MARKETPLACE_CHECK}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PATCHMAN_IMPL
              value: ${PATCHMAN_IMPL}
            - name: PATCHMAN_HOST
              value: ${PATCHMAN_HOST}
            - name: PLAYBOOK_DISPATCHER_IMPL
              value: ${PLAYBOOK_DISPATCHER_IMPL}
            - name: PLAYBOOK_DISPATCHER_HOST
              value: ${PLAYBOOK_DISPATCHER_HOST}
            - name: PLAYBOOK_DISPATCHER_AUTH
              valueFrom:
                secretKeyRef:
                  key: key
                  name: psk-playbook-dispatcher
            - name: PLATFORM_HOSTNAME_URL
              value: ${PLATFORM_HOSTNAME_URL}
            - name: PATH_PREFIX
              value: ${PATH_PREFIX}
            - name: RBAC_IMPL
              value: ${RBAC_IMPL}
            - name: RBAC_HOST
              value: http://${RBAC_HOST}:8080
            - name: RBAC_ENFORCE
              value: ${RBAC_ENFORCE}
            - name: RECEPTOR_IMPL
              value: ${RECEPTOR_IMPL}
            - name: RECEPTOR_HOST
              value: ${RECEPTOR_CONTROLLER_HOST}
            - name: REDIS_ENABLED
              value: 'true'
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: redis
            - name: SOURCES_IMPL
              value: ${SOURCES_IMPL}
            - name: SOURCES_PORT
              value: ${SOURCES_PORT}
            - name: SOURCES_HOST
              value: ${SOURCES_HOST}
            - name: SSG_IMPL
              value: ${SSG_IMPL}
            - name: SSG_HOST
              value: ${SSG_HOST}
            - name: USERS_IMPL
              value: ${USERS_IMPL}
            - name: USERS_HOST
              value: https://${BACKOFFICE_HOST}
            - name: USERS_INSECURE
              value: ${USERS_INSECURE}
            - name: USERS_AUTH
              valueFrom:
                secretKeyRef:
                  key: token
                  name: backoffice
            - name: USERS_ENV
              value: ${BACKOFFICE_CLIENT_ENV}
            - name: VULNERABILITIES_IMPL
              value: ${VULNERABILITIES_IMPL}
            - name: VULNERABILITIES_HOST
              value: ${VULNERABILITIES_HOST}
            - name: XJOIN_SEARCH_URL
              value: http://${XJOIN_SEARCH_URL}:4000/graphql
            inheritEnv: true
            args:
              - /bin/sh
              - -c
              - ${MIGRATION_COMMAND}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 9002
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 9002
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumes:
          - name: rds-cacert
            secret:
              secretName: rds-client-ca
        volumeMounts:
          - mountPath: /opt/certs/
            name: rds-cacert
            readOnly: true
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        env:
          - name: ADVISOR_IMPL
            value: ${ADVISOR_IMPL}
          - name: ADVISOR_HOST
            value: ${ADVISOR_HOST}
          - name: BODY_PARSER_LIMIT
            value: ${BODY_PARSER_LIMIT}
          - name: COMPLIANCE_IMPL
            value: ${COMPLIANCE_IMPL}
          - name: COMPLIANCE_HOST
            value: ${COMPLIANCE_HOST}
          - name: CONTENT_SERVER_HOST
            value: ${ADVISOR_HOST}
          - name: CONFIG_MANAGER_IMPL
            value: ${CONFIG_MANAGER_IMPL}
          - name: CONFIG_MANAGER_PORT
            value: ${CONFIG_MANAGER_PORT}
          - name: CONFIG_MANAGER_HOST
            value: ${CONFIG_MANAGER_HOST}
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                key: db.host
                name: remediations-db
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                key: db.user
                name: remediations-db
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: db.password
                name: remediations-db
          - name: DB_CA
            value: /opt/certs/rds-cacert
          - name: DB_SSL_ENABLED
            value: ${DB_SSL_ENABLED}
          - name: FIFI_TEXT_UPDATES
            value: 'true'
          - name: FIFI_TEXT_UPDATE_INTERVAL
            value: '5000'
          - name: FIFI_TEXT_UPDATE_FULL
            value: 'true'
          - name: DEMO_MODE
            value: 'false'
          - name: INVENTORY_IMPL
            value: ${INVENTORY_IMPL}
          - name: INVENTORY_HOST
            value: ${INVENTORY_HOST}
          - name: LOG_LEVEL
            value: ${LOG_LEVEL}
          - name: LOG_CW_ENABLED
            value: ${LOG_CW_ENABLED}
          - name: LOG_CW_KEY
            valueFrom:
              secretKeyRef:
                key: aws_access_key_id
                name: cloudwatch
          - name: LOG_CW_SECRET
            valueFrom:
              secretKeyRef:
                key: aws_secret_access_key
                name: cloudwatch
          - name: LOG_CW_GROUP
            valueFrom:
              secretKeyRef:
                key: log_group_name
                name: cloudwatch
          - name: LOG_CW_REGION
            valueFrom:
              secretKeyRef:
                key: aws_region
                name: cloudwatch
          - name: MARKETPLACE_CHECK
            value: ${MARKETPLACE_CHECK}
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: PATCHMAN_IMPL
            value: ${PATCHMAN_IMPL}
          - name: PATCHMAN_HOST
            value: ${PATCHMAN_HOST}
          - name: PLAYBOOK_DISPATCHER_IMPL
            value: ${PLAYBOOK_DISPATCHER_IMPL}
          - name: PLAYBOOK_DISPATCHER_HOST
            value: ${PLAYBOOK_DISPATCHER_HOST}
          - name: PLAYBOOK_DISPATCHER_AUTH
            valueFrom:
              secretKeyRef:
                key: key
                name: psk-playbook-dispatcher
          - name: PLATFORM_HOSTNAME_URL
            value: ${PLATFORM_HOSTNAME_URL}
          - name: PATH_PREFIX
            value: ${PATH_PREFIX}
          - name: RBAC_IMPL
            value: ${RBAC_IMPL}
          - name: RBAC_HOST
            value: ${RBAC_HOST}
          - name: RBAC_ENFORCE
            value: ${RBAC_ENFORCE}
          - name: RECEPTOR_IMPL
            value: ${RECEPTOR_IMPL}
          - name: RECEPTOR_HOST
            value: ${RECEPTOR_CONTROLLER_HOST}
          - name: REDIS_ENABLED
            value: 'true'
          - name: REDIS_HOST
            value: redis
          - name: REDIS_PORT
            value: '6379'
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: redis
          - name: SOURCES_IMPL
            value: ${SOURCES_IMPL}
          - name: SOURCES_PORT
            value: ${SOURCES_PORT}
          - name: SOURCES_HOST
            value: ${SOURCES_HOST}
          - name: SSG_IMPL
            value: ${SSG_IMPL}
          - name: SSG_HOST
            value: ${SSG_HOST}
          - name: USERS_IMPL
            value: ${USERS_IMPL}
          - name: USERS_HOST
            value: https://${BACKOFFICE_HOST}
          - name: USERS_INSECURE
            value: ${USERS_INSECURE}
          - name: USERS_AUTH
            valueFrom:
              secretKeyRef:
                key: token
                name: backoffice
          - name: USERS_ENV
            value: ${BACKOFFICE_CLIENT_ENV}
          - name: VULNERABILITIES_IMPL
            value: ${VULNERABILITIES_IMPL}
          - name: VULNERABILITIES_HOST
            value: ${VULNERABILITIES_HOST}
          - name: XJOIN_SEARCH_URL
            value: http://${XJOIN_SEARCH_URL}:4000/graphql

parameters:
- name: ADVISOR_IMPL
  value: ${ADVISOR_IMPL}
- name: ADVISOR_HOST
  value: ${ADVISOR_HOST}
- name: BODY_PARSER_LIMIT
  value: ${BODY_PARSER_LIMIT}
- name: COMPLIANCE_IMPL
  value: ${COMPLIANCE_IMPL}
- name: COMPLIANCE_HOST
  value: ${COMPLIANCE_HOST}
- name: CONTENT_SERVER_HOST
  value: ${ADVISOR_HOST}
- name: CONFIG_MANAGER_IMPL
  value: ${CONFIG_MANAGER_IMPL}
- name: CONFIG_MANAGER_PORT
  value: ${CONFIG_MANAGER_PORT}
- name: CONFIG_MANAGER_HOST
  value: ${CONFIG_MANAGER_HOST}
- name: DB_HOST
  valueFrom:
    secretKeyRef:
      key: db.host
      name: remediations-db
- name: DB_USERNAME
  valueFrom:
    secretKeyRef:
      key: db.user
      name: remediations-db
- name: DB_PASSWORD
  valueFrom:
    secretKeyRef:
      key: db.password
      name: remediations-db
- name: DB_CA
  value: /opt/certs/rds-cacert
- name: DB_SSL_ENABLED
  value: ${DB_SSL_ENABLED}
- name: FIFI_TEXT_UPDATES
  value: 'true'
- name: FIFI_TEXT_UPDATE_INTERVAL
  value: '5000'
- name: FIFI_TEXT_UPDATE_FULL
  value: 'true'
- name: DEMO_MODE
  value: 'false'
- name: INVENTORY_IMPL
  value: ${INVENTORY_IMPL}
- name: INVENTORY_HOST
  value: ${INVENTORY_HOST}
- name: LOG_LEVEL
  value: ${LOG_LEVEL}
- name: LOG_CW_ENABLED
  value: ${LOG_CW_ENABLED}
- name: LOG_CW_KEY
  valueFrom:
    secretKeyRef:
      key: aws_access_key_id
      name: cloudwatch
- name: LOG_CW_SECRET
  valueFrom:
    secretKeyRef:
      key: aws_secret_access_key
      name: cloudwatch
- name: LOG_CW_GROUP
  valueFrom:
    secretKeyRef:
      key: log_group_name
      name: cloudwatch
- name: LOG_CW_REGION
  valueFrom:
    secretKeyRef:
      key: aws_region
      name: cloudwatch
- name: MARKETPLACE_CHECK
  value: ${MARKETPLACE_CHECK}
- name: NAMESPACE
  valueFrom:
    fieldRef:
      fieldPath: metadata.namespace
- name: PATCHMAN_IMPL
  value: ${PATCHMAN_IMPL}
- name: PATCHMAN_HOST
  value: ${PATCHMAN_HOST}
- name: PLAYBOOK_DISPATCHER_IMPL
  value: ${PLAYBOOK_DISPATCHER_IMPL}
- name: PLAYBOOK_DISPATCHER_HOST
  value: ${PLAYBOOK_DISPATCHER_HOST}
- name: PLAYBOOK_DISPATCHER_AUTH
  valueFrom:
    secretKeyRef:
      key: key
      name: psk-playbook-dispatcher
- name: PLATFORM_HOSTNAME_URL
  value: ${PLATFORM_HOSTNAME_URL}
- name: PATH_PREFIX
  value: ${PATH_PREFIX}
- name: RBAC_IMPL
  value: ${RBAC_IMPL}
- name: RBAC_HOST
  value: ${RBAC_HOST}
- name: RBAC_ENFORCE
  value: ${RBAC_ENFORCE}
- name: RECEPTOR_IMPL
  value: ${RECEPTOR_IMPL}
- name: RECEPTOR_HOST
  value: ${RECEPTOR_CONTROLLER_HOST}
- name: REDIS_ENABLED
  value: 'true'
- name: REDIS_HOST
  value: redis
- name: REDIS_PORT
  value: '6379'
- name: REDIS_PASSWORD
  valueFrom:
    secretKeyRef:
      key: password
      name: redis
- name: SOURCES_IMPL
  value: ${SOURCES_IMPL}
- name: SOURCES_PORT
  value: ${SOURCES_PORT}
- name: SOURCES_HOST
  value: ${SOURCES_HOST}
- name: SSG_IMPL
  value: ${SSG_IMPL}
- name: SSG_HOST
  value: ${SSG_HOST}
- name: USERS_IMPL
  value: ${USERS_IMPL}
- name: USERS_HOST
  value: https://${BACKOFFICE_HOST}
- name: USERS_INSECURE
  value: ${USERS_INSECURE}
- name: USERS_AUTH
  valueFrom:
    secretKeyRef:
      key: token
      name: backoffice
- name: USERS_ENV
  value: ${BACKOFFICE_CLIENT_ENV}
- name: VULNERABILITIES_IMPL
  value: ${VULNERABILITIES_IMPL}
- name: VULNERABILITIES_HOST
  value: ${VULNERABILITIES_HOST}
- name: XJOIN_SEARCH_URL
  value: http://${XJOIN_SEARCH_URL}:4000/graphql
