NAMESPACE = 'remediations-ci'

def notify(subject, body, color) {
    message = subject
    if (body != null) {
        message += " | ${body}"
    }

    slackSend message: message, color: color, channel: '#insights-remediations'
}

def notifyOnFailure(Closure step) {
    try {
        step()
    } catch (e) {
        notify("[${env.JOB_NAME}] Build failed", "See ${env.BUILD_URL}console", "danger")
        throw e
    }
}

node {
    notifyOnFailure {
        notify("[${env.JOB_NAME}] Build started", null, "#439FE0")

        env.NODEJS_HOME = "${tool 'node-10'}"
        env.PATH="${env.NODEJS_HOME}/bin:${env.PATH}"

        checkout scm

        sh 'git rev-parse HEAD'

        stage('build') {
            sh 'npm ci'
        }

        stage('verify') {
            sh 'npm run verify'
        }

        stage('build image') {
            openshiftBuild(buildConfig: "remediations", showBuildLogs: "true", namespace: NAMESPACE)
        }

        stage('deploy') {
            openshiftDeploy(deploymentConfig: "remediations", namespace: NAMESPACE)
            sh "oc rollout status --namespace=${NAMESPACE} dc/remediations"
            notify("[${env.JOB_NAME}] Deployment finished", null, "good")
        }
    }
}
