apiVersion: v1
kind: Template
metadata:
  name: playbooks-ssg
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: playbooks
    name: playbooks-ssg
  spec:
    minReadySeconds: 15
    progressDeadlineSeconds: 600
    replicas: ${{SSG_REPLICAS}}
    revisionHistoryLimit: 9
    selector:
      matchLabels:
        app: playbooks
        service: playbooks-ssg
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: playbooks
          service: playbooks-ssg
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - playbooks
                  - key: service
                    operator: In
                    values:
                    - playbooks-ssg
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - playbooks
                  - key: service
                    operator: In
                    values:
                    - playbooks-ssg
                topologyKey: kubernetes.io/hostname
              weight: 99
        containers:
        - image: quay.io/cloudservices/playbooks-ssg:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /playbooks
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          name: playbooks-ssg
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /playbooks
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            limits:
              cpu: ${LIMITS_CPU}
              memory: 512Mi
            requests:
              cpu: ${REQUESTS_CPU}
              memory: 256Mi
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: quay-cloudservices-pull
        - name: rh-registry-pull
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: playbooks
    name: playbooks-ssg
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: playbooks
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:
- name: REQUESTS_CPU
  value: 250m
- name: LIMITS_CPU
  value: '1'
- description: The number of replicas to use for SSG
  name: SSG_REPLICAS
  value: '1'
- description: Image tag
  name: IMAGE_TAG
  required: true
