{
 "title": "Remediations",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(remediations_http_request_duration_seconds_count{namespace=~\"remediations-.*\"}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max API Memory Quota",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "percentunit",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"remediations-.*\",container=\"remediations\"}) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"remediations-.*\",container=\"remediations\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max API Pod Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(up{namespace=~\"remediations-.*\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(remediations_connector_hit{namespace=~\"remediations-.*\"}[$__range])) / (sum(increase(remediations_connector_hit{namespace=~\"remediations-.*\"}[$__range])) + sum(increase(remediations_connector_miss{namespace=~\"remediations-.*\"}[$__range])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"remediations-.*\",container=~\"remediations|redis\"}[5m])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "4xx ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "format": "percentunit",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(remediations_http_request_duration_seconds_count{namespace=~\"remediations-.*\", status_code=~\"4.*\"}[$__range])) / sum(increase(remediations_http_request_duration_seconds_count{namespace=~\"remediations-.*\"}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max SSG Memory Quota",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "format": "percentunit",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"remediations-.*\",container=\"playbooks-ssg\"}) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"remediations-.*\",container=\"playbooks-ssg\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=~\"remediations-.*\"}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Connector Error Ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(remediations_connector_error{kubernetes_namespace=\"remediations-prod\"}[$__range]) or up * 0) / sum(increase(remediations_connector_summary_count[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "5xx ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "format": "percentunit",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(remediations_http_request_duration_seconds_count{namespace=~\"remediations-.*\", status_code=~\"5.*\"}[$__range])) / sum(increase(remediations_http_request_duration_seconds_count{namespace=~\"remediations-.*\"}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Redis Memory Quota",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "format": "percentunit",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"remediations-.*\",container=\"redis\"}) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"remediations-.*\",container=\"redis\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Playbooks Generated",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(remediations_playbooks_generated[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Playbooks Executed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(remediations_playbooks_executed{namespace=~\"remediations-.*\"}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processed messages",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(remediations_consumer_messages_total{namespace=~\"remediations-.*\"}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(remediations_http_request_duration_seconds_count{namespace=~\"remediations-.*\"}[$__range])) by (status_code) > 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Connector Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(remediations_connector_error{namespace=~\"remediations-.*\"}[$__range])) by (connector, method) > 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(remediations_http_request_duration_seconds_count{namespace=~\"remediations-.*\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "request count per 1m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hosts Removed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(remediations_consumer_remove_total{namespace=~\"remediations-.*\", result=\"success\"}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Message Errors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(remediations_consumer_remove_total{namespace=~\"remediations-.*\", result=~\"error.*\"}[$__range])) + sum(increase(remediations_consumer_receptor_total{namespace=~\"remediations-.*\", result=~\"error.*\"}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Consumer Lag",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(kafka_consumergroup_group_lag{namespace=~\"platform-mq-.*\", group=\"remediations-consumer\"}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_time_bucket{exported_service=\"remediations\"}[5m])) by (le)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}} ms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(remediations_http_request_duration_seconds_sum[1m])) / sum(rate(remediations_http_request_duration_seconds_count[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "avg response time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FiFi",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "playbook execute requests",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 23 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(remediations_playbooks_executed[$__range])) or vector(0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "executor acks",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 23 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(remediations_consumer_receptor_total{type=\"playbook_run_ack\"}[$__range]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "total processed",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 23 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(remediations_consumer_receptor_total{result=\"processed\"}[$__range]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "runs cleaned",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 23 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(max_over_time(remediations_cleaner_updated_total{entity=\"runs\", app!=\"prometheus-push\", job=~\"remediations-prod\\\\|.*\"}[$__range]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Cleaner runs",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(remediations_cleaner_updated_total{app!=\"prometheus-push\", job=~\"remediations-prod\\\\|.*\"}) by (entity) - sum(remediations_cleaner_updated_total{app!=\"prometheus-push\", job=~\"remediations-prod\\\\|.*\"} offset 1m) by (entity) > 0",
       "legendFormat": "{{entity}}"
      }
     ]
    },
    {
     "title": "playbook cancel requests",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 25 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(remediations_playbooks_canceled[$__range])) or vector(0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "executor misses",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 25 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(remediations_consumer_receptor_executor_not_found[$__range]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "parser errors",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 25 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(remediations_consumer_receptor_total{result=\"error_parse\"}[$__range]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "executors cleaned",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 25 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(max_over_time(remediations_cleaner_updated_total{entity=\"executors\", app!=\"prometheus-push\", job=~\"remediations-prod\\\\|.*\"}[$__range]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "lock mismatch",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 27 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(remediations_fifi_etag_checks{status=\"mismatch\"}[$__range]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "lost receptor messages",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 27 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(increase(remediations_consumer_lost_messages_total[$__range]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "processing errors",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 27 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(remediations_consumer_receptor_total{result=\"error\"}[$__range]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "systems cleaned",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 27 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(max_over_time(remediations_cleaner_updated_total{entity=\"systems\", app!=\"prometheus-push\", job=~\"remediations-prod\\\\|.*\"}[$__range]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "sat-receptor responses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(remediations_consumer_receptor_total{result=\"processed\"}[1m])) by (type) > 0",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{type}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "playbook_run_cancel_ack statuses",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "sum(increase(remediations_consumer_receptor_cancel_ack_total[$__range])) by (status)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "RBAC rejections",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "sum(increase(remediations_rbac_errors_generated[$__range])) by (rbacPermission)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "sat-receptor responses",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "sum(increase(remediations_consumer_receptor_total[$__range])) by (result, type) > 0",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka consumer lag",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_group_lag{namespace=~\"platform-mq-.*\", group=\"remediations-consumer\"}) by (topic, group)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{topic}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"remediations-.*\",container=\"remediations-consumer\"}[5m])",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "MQ Errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(remediations_consumer_receptor_total{result=~\"error.*\"}[1m])) by (result)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "receptor-{{result}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(increase(remediations_consumer_remove_total{result=~\"error.*\"}[1m])) by (result)",
       "legendFormat": "inventory-{{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connectors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Hits",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 25 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(increase(remediations_connector_hit{namespace=~\"remediations-.*\"}[$__range]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Cache Misses",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 25 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(increase(remediations_connector_miss{namespace=~\"remediations-.*\"}[$__range]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Connector Errors",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 25 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(remediations_connector_error{namespace=~\"remediations-.*\"}[$__range]) or up * 0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Connector Response Times (0.5)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(max_over_time(remediations_connector_summary{quantile=\"0.5\", namespace=~\"remediations-.*\"}[1m])) by (connector, method)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Connector Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(remediations_connector_error{namespace=~\"remediations-.*\"}[1m])) by (connector, method)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Connector Response Times (0.95)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(max_over_time(remediations_connector_summary{quantile=\"0.95\", namespace=~\"remediations-.*\"}[1m])) by (connector, method)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"remediations-.*\",container=\"remediations\"}[5m])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{pod_name}}:{{container_name}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Percentage of CPU limit consumed",
     "type": "graph",
     "description": "CPU consumption plotted against configured CPU limit of service",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"remediations-.*\",container=\"remediations\"}[1m])) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"remediations-.*\",container=\"remediations\"})"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{namespace=~\"remediations-.*\",container=\"remediations\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Percentage of memory limit consumed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"remediations-.*\",container=\"remediations\"}) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"remediations-.*\",container=\"remediations\"})"
      }
     ]
    },
    {
     "title": "Database Query Times",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum(increase(remediations_db_histogram_bucket{namespace=~\"remediations-.*\"}[5m])) by (le)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{le}} ms",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Number of pods",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(up{namespace=~\"remediations-.*\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"remediations-.*\",container=\"redis\"}[5m])",
       "legendFormat": "{{pod_name}}:{{container_name}}"
      }
     ]
    },
    {
     "title": "Percentage of CPU limit consumed",
     "type": "graph",
     "description": "CPU consumption plotted against configured CPU limit of service",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"remediations-.*\",container=\"redis\"}[5m])) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"remediations-.*\",container=\"redis\"})"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{namespace=~\"remediations-.*\",container=\"redis\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Percentage of memory limit consumed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"remediations-.*\",container=\"redis\"}) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"remediations-.*\",container=\"redis\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "SSG Providers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"remediations-.*\",container=\"playbooks-ssg\"}[5m])",
       "legendFormat": "{{pod_name}}:{{container_name}}"
      }
     ]
    },
    {
     "title": "Percentage of CPU limit consumed",
     "type": "graph",
     "description": "CPU consumption plotted against configured CPU limit of service",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"remediations-.*\",container=\"redis\"}[5m])) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"remediations-.*\",container=\"redis\"})"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{namespace=~\"remediations-.*\", container=\"playbooks-ssg\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Percentage of memory limit consumed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"remediations-.*\",container=\"playbooks-ssg\"}) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"remediations-.*\",container=\"playbooks-ssg\"})"
      }
     ]
    }
   ]
  }
 ]
}